/**
 * World-Class Hotel Booking Engine
  * Handles availability, dynamic pricing, and reservation management
   */

   export type RoomType = 'single' | 'double' | 'suite' | 'family' | 'deluxe';

   export interface Room {
     id: string;
       type: RoomType;
         name: string;
           description: string;
             basePrice: number;
               maxOccupancy: number;
                 amenities: string[];
                   images: string[];
                     size: number;
                     }

                     export interface DateRange {
                       checkIn: Date;
                         checkOut: Date;
                         }

                         export interface AvailabilityResult {
                           room: Room;
                             available: boolean;
                               totalPrice: number;
                                 nightCount: number;
                                   pricePerNight: number;
                                   }

                                   export interface Reservation {
                                     id: string;
                                       roomId: string;
                                         guestName: string;
                                           guestEmail: string;
                                             guestPhone: string;
                                               checkIn: Date;
                                                 checkOut: Date;
                                                   guestCount: number;
                                                     totalPrice: number;
                                                       status: 'pending' | 'confirmed' | 'cancelled';
                                                         specialRequests?: string;
                                                           createdAt: Date;
                                                           }

                                                           export interface PricingRules {
                                                             weekendMultiplier: number;
                                                               seasonalMultipliers: Record<string, number>;
                                                                 earlyBirdDiscount: number;
                                                                   lastMinuteDiscount: number;
                                                                     lengthOfStayDiscounts: { nights: number; discount: number }[];
                                                                     }

                                                                     export const DEFAULT_PRICING_RULES: PricingRules = {
                                                                       weekendMultiplier: 1.25,
                                                                         seasonalMultipliers: { winter: 0.9, spring: 1.0, summer: 1.3, autumn: 1.1 },
                                                                           earlyBirdDiscount: 10,
                                                                             lastMinuteDiscount: 15,
                                                                               lengthOfStayDiscounts: [
                                                                                   { nights: 3, discount: 5 },
                                                                                       { nights: 7, discount: 10 },
                                                                                           { nights: 14, discount: 15 },
                                                                                             ],
                                                                                             };

                                                                                             export class BookingEngine {
                                                                                               private rooms: Room[];
                                                                                                 private reservations: Reservation[] = [];
                                                                                                   private pricingRules: PricingRules;

                                                                                                     constructor(rooms: Room[], pricingRules: PricingRules = DEFAULT_PRICING_RULES) {
                                                                                                         this.rooms = rooms;
                                                                                                             this.pricingRules = pricingRules;
                                                                                                               }
                                                                                                               
                                                                                                                 private calculateNights(checkIn: Date, checkOut: Date): number {
                                                                                                                     const diffMs = checkOut.getTime() - checkIn.getTime();
                                                                                                                         return Math.ceil(diffMs / (1000 * 60 * 60 * 24));
                                                                                                                           }
                                                                                                                           
                                                                                                                             private getSeason(date: Date): string {
                                                                                                                                 const month = date.getMonth();
                                                                                                                                     if (month >= 11 || month <= 1) return 'winter';
                                                                                                                                         if (month >= 2 && month <= 4) return 'spring';
                                                                                                                                             if (month >= 5 && month <= 7) return 'summer';
                                                                                                                                                 return 'autumn';
                                                                                                                                                   }
                                                                                                                                                   
                                                                                                                                                     private isWeekend(date: Date): boolean {
                                                                                                                                                         const day = date.getDay();
                                                                                                                                                             return day === 0 || day === 6;
                                                                                                                                                               }
                                                                                                                                                               
                                                                                                                                                                 public calculatePrice(room: Room, dateRange: DateRange): number {
                                                                                                                                                                     const nights = this.calculateNights(dateRange.checkIn, dateRange.checkOut);
                                                                                                                                                                         let totalPrice = 0;
                                                                                                                                                                             const current = new Date(dateRange.checkIn);
                                                                                                                                                                                 for (let i = 0; i < nights; i++) {
                                                                                                                                                                                       let nightPrice = room.basePrice;
                                                                                                                                                                                             const season = this.getSeason(current);
                                                                                                                                                                                                   nightPrice *= this.pricingRules.seasonalMultipliers[season] || 1.0;
                                                                                                                                                                                                         if (this.isWeekend(current)) {
                                                                                                                                                                                                                 nightPrice *= this.pricingRules.weekendMultiplier;
                                                                                                                                                                                                                       }
                                                                                                                                                                                                                             totalPrice += nightPrice;
                                                                                                                                                                                                                                   current.setDate(current.getDate() + 1);
                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                           const losDiscount = this.getLengthOfStayDiscount(nights);
                                                                                                                                                                                                                                               totalPrice *= 1 - losDiscount / 100;
                                                                                                                                                                                                                                                   const daysUntilCheckIn = this.calculateNights(new Date(), dateRange.checkIn);
                                                                                                                                                                                                                                                       if (daysUntilCheckIn >= 30) {
                                                                                                                                                                                                                                                             totalPrice *= 1 - this.pricingRules.earlyBirdDiscount / 100;
                                                                                                                                                                                                                                                                 } else if (daysUntilCheckIn <= 3) {
                                                                                                                                                                                                                                                                       totalPrice *= 1 - this.pricingRules.lastMinuteDiscount / 100;
                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                               return Math.round(totalPrice * 100) / 100;
                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                   private getLengthOfStayDiscount(nights: number): number {
                                                                                                                                                                                                                                                                                       let discount = 0;
                                                                                                                                                                                                                                                                                           for (const rule of this.pricingRules.lengthOfStayDiscounts) {
                                                                                                                                                                                                                                                                                                 if (nights >= rule.nights) discount = rule.discount;
                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                         return discount;
                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                             public isRoomAvailable(roomId: string, dateRange: DateRange): boolean {
                                                                                                                                                                                                                                                                                                                 const conflicting = this.reservations.filter((res) => {
                                                                                                                                                                                                                                                                                                                       if (res.roomId !== roomId) return false;
                                                                                                                                                                                                                                                                                                                             if (res.status === 'cancelled') return false;
                                                                                                                                                                                                                                                                                                                                   return dateRange.checkIn < res.checkOut && dateRange.checkOut > res.checkIn;
                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                           return conflicting.length === 0;
                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                               public searchAvailability(dateRange: DateRange, guestCount: number): AvailabilityResult[] {
                                                                                                                                                                                                                                                                                                                                                   const nights = this.calculateNights(dateRange.checkIn, dateRange.checkOut);
                                                                                                                                                                                                                                                                                                                                                       return this.rooms
                                                                                                                                                                                                                                                                                                                                                             .filter((room) => room.maxOccupancy >= guestCount)
                                                                                                                                                                                                                                                                                                                                                                   .map((room) => {
                                                                                                                                                                                                                                                                                                                                                                           const available = this.isRoomAvailable(room.id, dateRange);
                                                                                                                                                                                                                                                                                                                                                                                   const totalPrice = this.calculatePrice(room, dateRange);
                                                                                                                                                                                                                                                                                                                                                                                           return {
                                                                                                                                                                                                                                                                                                                                                                                                     room,
                                                                                                                                                                                                                                                                                                                                                                                                               available,
                                                                                                                                                                                                                                                                                                                                                                                                                         totalPrice,
                                                                                                                                                                                                                                                                                                                                                                                                                                   nightCount: nights,
                                                                                                                                                                                                                                                                                                                                                                                                                                             pricePerNight: Math.round((totalPrice / nights) * 100) / 100,
                                                                                                                                                                                                                                                                                                                                                                                                                                                     };
                                                                                                                                                                                                                                                                                                                                                                                                                                                           })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .sort((a, b) => a.totalPrice - b.totalPrice);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     public createReservation(data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         roomId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             guestName: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 guestEmail: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     guestPhone: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         dateRange: DateRange;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             guestCount: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 specialRequests?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }): Reservation | { error: string } {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!this.isRoomAvailable(data.roomId, data.dateRange)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return { error: 'Room is not available for the selected dates' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const room = this.rooms.find((r) => r.id === data.roomId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!room) return { error: 'Room not found' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (data.guestCount > room.maxOccupancy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return { error: 'Guest count exceeds room capacity' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const reservation: Reservation = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 id: `RES_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       roomId: data.roomId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             guestName: data.guestName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   guestEmail: data.guestEmail,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         guestPhone: data.guestPhone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               checkIn: data.dateRange.checkIn,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     checkOut: data.dateRange.checkOut,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           guestCount: data.guestCount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 totalPrice: this.calculatePrice(room, data.dateRange),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       status: 'pending',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             specialRequests: data.specialRequests,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   createdAt: new Date(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           this.reservations.push(reservation);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return reservation;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   public confirmReservation(reservationId: string): boolean {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const reservation = this.reservations.find((r) => r.id === reservationId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (reservation && reservation.status === 'pending') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 reservation.status = 'confirmed';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   public getReservations(filter?: { status?: Reservation['status'] }): Reservation[] {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (filter?.status) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return this.reservations.filter((r) => r.status === filter.status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return [...this.reservations];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         public getOccupancyRate(dateRange: DateRange): number {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const totalRooms = this.rooms.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (totalRooms === 0) return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const occupied = this.rooms.filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (room) => !this.isRoomAvailable(room.id, dateRange)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ).length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return Math.round((occupied / totalRooms) * 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
