import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    };

    serve(async (req) => {
      if (req.method === "OPTIONS") {
          return new Response("ok", { headers: corsHeaders });
            }

              try {
                  const { imageUrl, imageLabel } = await req.json();

                      if (!imageUrl) {
                            return new Response(
                                    JSON.stringify({ error: "imageUrl is required" }),
                                            { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                  );
                                                      }

                                                          const openaiKey = Deno.env.get("OPENAI_API_KEY");
                                                              if (!openaiKey) {
                                                                    return new Response(
                                                                            JSON.stringify({ error: "OPENAI_API_KEY not configured" }),
                                                                                    { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                          );
                                                                                              }

                                                                                                  const systemPrompt = `Du bist ein professioneller Fotograf und Art Director fuer Hotelfotografie und Gastronomie.
                                                                                                  Analysiere das Bild und erstelle einen praezisen Style-Prompt auf Englisch fuer DALL-E / Stable Diffusion.
                                                                                                  Der Prompt soll folgende visuelle Elemente beschreiben:
                                                                                                  - Teller, Geschirr, Besteck und Glaeser (Material, Form, Farbe, Stil)
                                                                                                  - Tischdecke, Unterlagen, Dekorationselemente
                                                                                                  - Beleuchtung (warm/kalt, Richtung, Intensitaet, Bokeh)
                                                                                                  - Farbpalette und Stimmung (elegant, rustikal, modern, usw.)
                                                                                                  - Komposition und Perspektive (Vogelperspektive, seitlich, 45 Grad)
                                                                                                  - Hintergrund und Ambiente (Restaurant-Interieur, Outdoor, Studio)
                                                                                                  Schreibe nur den Style-Prompt, keine Erklaerungen. Maximal 150 Woerter. Auf Englisch.`;

                                                                                                      const userPrompt = imageLabel
                                                                                                            ? `Analysiere dieses Bild (Label: "${imageLabel}") und erstelle einen detaillierten Style-Prompt.`
                                                                                                                  : "Analysiere dieses Bild und erstelle einen detaillierten Style-Prompt.";
                                                                                                                  
                                                                                                                      const response = await fetch("https://api.openai.com/v1/chat/completions", {
                                                                                                                            method: "POST",
                                                                                                                                  headers: {
                                                                                                                                          "Authorization": `Bearer ${openaiKey}`,
                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                        },
                                                                                                                                                              body: JSON.stringify({
                                                                                                                                                                      model: "gpt-4o",
                                                                                                                                                                              messages: [
                                                                                                                                                                                        { role: "system", content: systemPrompt },
                                                                                                                                                                                                  {
                                                                                                                                                                                                              role: "user",
                                                                                                                                                                                                                          content: [
                                                                                                                                                                                                                                        { type: "text", text: userPrompt },
                                                                                                                                                                                                                                                      { type: "image_url", image_url: { url: imageUrl, detail: "high" } },
                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                            max_tokens: 400,
                                                                                                                                                                                                                                                                                                    temperature: 0.3,
                                                                                                                                                                                                                                                                                                          }),
                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                  if (!response.ok) {
                                                                                                                                                                                                                                                                                                                        const err = await response.text();
                                                                                                                                                                                                                                                                                                                              console.error("OpenAI API error:", err);
                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                            JSON.stringify({ error: "OpenAI API error", details: err }),
                                                                                                                                                                                                                                                                                                                                                    { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                  const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                                      const styleDescription = data.choices?.[0]?.message?.content?.trim() || "";
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                          return new Response(
                                                                                                                                                                                                                                                                                                                                                                                JSON.stringify({ styleDescription, usage: data.usage }),
                                                                                                                                                                                                                                                                                                                                                                                      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                console.error("analyze-style-image error:", err);
                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                          JSON.stringify({ error: err.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      });
